services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure:3
    environment:
      ADMIN_API_KEY: 48B508EC-E715-48F6-AAC6-8218A1720F8D
      SPRING_DATA_MONGODB_URI: mongodb://host.docker.internal:27017/tripplanner?retryWrites=true&w=majority&connectTimeoutMS=30000&socketTimeoutMS=30000&serverSelectionTimeoutMS=30000&maxPoolSize=50&minPoolSize=10&maxIdleTimeMS=60000&waitQueueTimeoutMS=30000
      SPRING_DATA_MONGODB_DATABASE: tripplanner
      TELEGRAM_BOT_TOKEN: 7687419368:AAHRuN00r0_WBAkRVQA65e5q2B7zaU8xgHs
    ports:
      - "8080:8080"
    networks:
      - app-network
    container_name: app
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/healthcheck"]
      interval: 30s
      timeout: 5s
      retries: 3
    stop_grace_period: 30s
    stop_signal: SIGTERM
    init: true
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M

networks:
  app-network:
    name: trip-planner-network
    driver: bridge